"""Add mentions column to Comment

Revision ID: a9c44824c39b
Revises: 71f3cf5c26af
Create Date: 2025-05-29 22:21:02.220501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c44824c39b'
down_revision = '71f3cf5c26af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentions', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('mentions')

    # ### end Alembic commands ###
